//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public string Image { get; set; }
        public Nullable<int> DeptId { get; set; }
    
        public virtual tbl_Deparment tbl_Deparment { get; set; }
    }
}
